### ISSUE TITLE
Curve Maker not Installing! Please Help!

### ISSUE THREAD

**Issue by dotoleary** [tokjun/CurveMaker#13]
After installing Curve Maker from the extension tab and restarting slicer, Curve Maker does not appear in the informatics tab.

I get the following critical errors upon starting 3d slicer:

Stream Error:
File "", line 1
import imp;imp.load_source('CurveMaker', 'C:/Users/Mitchell O'Leary/AppData/Roaming/NA-MIC/Extensions-26813/CurveMaker/lib/Slicer-4.8/qt-scripted-modules/CurveMaker.py');del imp;
^
SyntaxError: invalid syntax

Qt Error:
loadSourceAsModule - Failed to load file "C:/Users/Mitchell O'Leary/AppData/Roaming/NA-MIC/Extensions-26813/CurveMaker/lib/Slicer-4.8/qt-scripted-modules/CurveMaker.py" as module "CurveMaker" !
Fail to instantiate module "CurveMaker"

**Comment by jamesobutler** [comment]
Since there wasn’t a follow-up here, I’ll provide one now for anyone that comes across this again.

The source of the error was not with the CurveMaker extension, but with Slicer importing modules where the path included a single quote such as “O’Leary” in the above case.

The issue was tracked as Slicer issue [4592](https://issues.slicer.org/view.php?id=4592) and was resolved with https://github.com/Slicer/Slicer/commit/e40af17987ff03931930d3c9ba198a0738f37f86. This commit was first included in Slicer stable 4.10.0
